//char firstChar = str.charArt(0);
//        String substring = str.substring(7);
//        System.out.println("Substring from index 7: " + substring);
//        int IndexOfComma = str.indexOf(" ,");
//        System.out.println("Index of Comma :" + IndexOfComma);
//        int lastIndexOfSpace = str.lastIndexOf();
//        System.out.println("Last index of space : ", +lastIndexOfSpace);
//        String str2 = "Hello, World!";
//        boolean isEqual = str.equals(str2);
//        System.out.println("Are the strings eual? ", +isEqual);
//        string str3 = "Hello, World!";
//        boolean isEqualIgnoreCase = str.equalsIgnoreCase(str3);
//        System.out.println("Are the strings equal ignoring case? " + isEqualIgnoreCase);
//        int compareToResult = str.compareTo(str2);
//        System.out.println("Compare to result :" + compareToResult);
//        int compareToIgnoreCaseResult = str.compareToIgnoreCaseResult = str.compareToIgnorecase(str3);
//        System.out.println("Compare to ignore case result :" + compareToResult);
//        String replaceString = str.replace("World", "Universe");
//        System.out.println("String after replacement: " + replaceString);
//        string strWithspace = "Hello, World!";
//        string trimemdstring = strWithspace.trim();
//        String lowerCaseString = str.toLowerCase();
//        System.out.println("Lower case string: " + lowerCaseString);
//        string UppercaseString = str.touppercase();
//        System.out.println("Upper case string :" + UppercaseString);
//        String[] splitstreing = str.split(",");
//        System.out.println("Split string :");
//        for (String s : splitString) {
//            System.out.println(s.trim());
//        }
